# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='priority',
            field=models.IntegerField(default=2147483647, unique=True),
        ),
    ]
